# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Beyond the Label"

locale: "en-GB"

title_separator: "-"

email: gd304@cam.ac.uk

description: >- An experimental project to bring enhanced label data to the public via QR or NFC codes in gallery.

words_per_minute: 200

baseurl: ""

url: "https://beyondthelabel.fitzmuseum.cam.ac.uk"

twitter_username: fitzwilliam_uk

github_username:  fitzwilliammuseum

github_repo: beyond-the-label

mailchimp-list: https://cam.us17.list-manage.com/subscribe/post?u=f30da66801c7549a27ffb3357&amp;id=741e719b5c

rights: AGPL

content_license: CC-BY

logo: "/images/logos/rainbow.png"

google_analytics: G-4LG0J4SM9Z

lang: EN_GB
timezone: Europe/London
permalink: pretty
encoding: "utf-8"
read_time: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions

collections:
   labels:
      output: true
      permalink: /:collection/:name
feed:
  collections:
    - labels
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby
